#!/bin/bash

echo
echo "Setting environment variables ..."
if [ "$1" == "-p" ]; then
    cp ../deploys/20151217/production/.env .env
else
    if [ ! -f .env ]; then
        cp ../deploys/20151217/local/.env .env
    fi
fi

echo
if [ "$1" == "-f" ] || [ "$1" == "-p" ]; then
    vendor/bin/doctrine orm:schema-tool:drop --force
fi
vendor/bin/doctrine orm:schema-tool:update --force

echo
echo "Generating proxies ..."
if [ "$1" == "-f" ] || [ "$1" == "-p" ]; then
    ls storage/framework/proxies/* | grep -v .gitignore | xargs rm -f
fi
vendor/bin/doctrine orm:generate:proxies

if [ "$1" == "-f" ] || [ "$1" == "-p" ]; then
    echo
    php artisan db:seed --force

    if [ "$1" == "-f" ]; then
        echo
        php artisan ide-helper:generate
        php artisan ide-helper:meta
    fi
fi

echo
php artisan cache:clear
php artisan clear-compiled
if [ "$1" == "-p" ]; then
    php artisan optimize
    php artisan route:cache
    php artisan config:cache
fi

echo
echo "Deleting temporary files ..."
ls storage/framework/sessions/* | grep -v .gitignore | xargs rm -f
ls storage/framework/vars/* | grep -v .gitignore | xargs rm -f
ls storage/framework/views/* | grep -v .gitignore | xargs rm -f
ls storage/logs/* | grep -v .gitignore | xargs rm -f